# .github/release.yml

changelog:
  exclude:
    labels:
      - duplicate
      - ignore-for-release
  categories:
    - title: 🏕 Features
      labels:
        - feature
    - title: 🏕 Enhancement
      labels:
        - enhancement
    - title: breaking changes
      labels:
        - breaking changes
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: 🐛 Bug
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
