# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - bug
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: 🐛 Bug
      labels:
        - bug
