# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - feature
    - title: 🏕 Enhancement
      labels:
        - enhancement
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: 🐛 Bug
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
